apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-app
  namespace: production

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: devops-app

  template:
    metadata:
      labels:
        app: devops-app

    spec:
      serviceAccountName: devops-admin

      containers:
      - name: devops-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 5000

        readinessProbe:
          httpGet:
            path: /health
            port: 5000

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
